$(document).ready(function() {
  // Block#: 6
  function on_Button_click(e) {
    try {
      // Block#: 61
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Label", 'Hello World');
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="Button"]').on('click', on_Button_click);
  $('[obj-name="MainScreen"]').show();
});
// Generated by snapp
// 582866-536851-682453-62166
